<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="ExampleRecord" type="ExampleRecordType"/>

  <xs:complexType name="ExampleRecordType">
    <xs:sequence>
      <xs:element name="Label" type="LabelType"/>
      <xs:element name="Note" type="xs:string" minOccurs="0"/>
      <xs:element name="Novelty" type="xs:string" minOccurs="0"/>
      <xs:element name="Status" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="AccessionAlias" type="xs:string" minOccurs="0"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Accession" type="xs:string" use="required"/>
    <xs:attribute name="Version" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="SchemaVersion" type="xs:string"/>
    <xs:attribute name="Curated" type="xs:string"/>
    <xs:anyAttribute namespace="##other" processContents="lax"/>
  </xs:complexType>

  <xs:complexType name="LabelType" mixed="true">
    <xs:sequence>
      <xs:element name="Emphasis" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lang" type="xs:string"/>
  </xs:complexType>

</xs:schema>
